name: Starfall
url: http://http://gmodstarfall.github.io/Starfall/
description: Sandbox engine for Garry's Mod

permalink: /:title/
exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile', 'Vagrantfile']

pygments: true
lsi: false
safe: true
